### ISSUE TITLE
PDF metadata requires sanitization

### ISSUE THREAD

**Issue by maxwellfunk** [GSA/idmanagement.gov#36]
#### Description of Issue: ####
Several posted PDF documents retain the metadata of the original document that was edited to create the pdf (e.g., original filename.docx).  Need to sanitize original metadata in these docs and reupload.

#### References (Docs, Links, Files): ####
![image](https://user-images.githubusercontent.com/57905080/126187681-d8135019-9245-4010-9498-57cc8d75173e.png)

#### Possible Solution ####
download, edit pdf to sanitize and reupload documents in the repository.

**Comment by maxwellfunk** [comment]
may require a bulk download of all .pdf docs, sanitization using acrobat standard or foxit phantom full edition and re-upload.

**Comment by JillTunick** [comment]
Turns out only some of the PDFs have old Word titles in their metadata and it's easy to delete it in the PDF File>Properties>Title field. I propose this solution to sanitize the metadata:

I'll download and go through the PDFs one by one, yank the old Word titles from those that have that metadata, save those cleaned PDFs in a folder, and then upload them, with the same filenames and the same labels, to replace the ones with funky metadata in the idmanagement.gov/docs/ area. I would use the History info to identify the older version of the cleaned document with the same filename and I'd delete the older version. 

Would that work?

**Comment by maxwellfunk** [comment]
modifying the properties manually is fine.

Note: We will not be able to modify digitally signed documents, so we will just update and sanitize as they are replaced.
