### ISSUE TITLE
SEO - Missing structured data markup - Home page

### ISSUE THREAD

**Issue by id2win** [GSA/idmanagement.gov#603]
There are many occurrences, lets POC with the home to see how this goes. If this can be achieved in one place and applied across all pages we can provide the remaining list. 

Issue 

Structured Data Markup is a way of marking up data that has been converted to HTML code in a way that search engines can understand. Search engines can then use this data to generate "rich snippets" on search results pages, e.g. adding images, review ratings, price, etc. within a search result. Having structured data markup on your pages can greatly boost the visibility of your site in search results.

Details - https://my2.siteimprove.com/Inspector/1163140/SeoV2New/Page?pageId=36096470619&impmd=4047A2DE150B72849C355FDFA2312F26&pageMode=Content#/issue/structuredmarkuppages/66

Fix 

While several markup formats are available, we recommend Google's [Structured Data Markup Helper](https://support.google.com/webmasters/answer/3069489?hl=en). It offers an easy way of marking up page elements so that Google can understand the data.

**Comment by claytonjbarnette** [comment]
@id2win @KonradMiles @SuGhadiali @TheInfinityBeyonder @JBPayne007

This is still a WIP for me on the PoC, since [The Sematic Web](https://www.w3.org/RDF/) can become a deep subject for us with so many pages and so much data, it will require some decisions to be make about: 

- Linking strategies 
- Which schemas to use
- Type of data to target
- Which pages or sections of a page to target
- How much or little tagging and linking should be do

**Structured Data:** ( [JSON-LD](http://json-ld.org/) | [Microdata](https://support.google.com/webmasters/answer/176035) ) and [Linked Data](https://en.wikipedia.org/wiki/Linked_data) introduced by Google and Facebook via [Schema,org](https://schema.org/), can help the website with visibility, and help people find related information on our sites better. But the level of tagging and marking up an organizations website data is dependent upon that organization's desire and level of effort they want to put into it. 

Google tries to make it easy with the *Structured Data Markup Helper*, but after a PoC, we will have to make some decisions about our data intent for each page for this to be effective in the long run.

**Comment by id2win** [comment]
@claytonjbarnette do you know the level of effort for this one page based on your research? This will help with my decision to work this or not. If overly complex and time consuming we may need to re-prioritize since this is not a content or material issue right now.

**Comment by claytonjbarnette** [comment]
@id2win The level of effort for this is medium to high, and I feel, determining what data to tag and the correct category and schema is beyond my decision level and would require a collective to decide. 

We can do the work once a clear path is present, but since we are governmental, making these determinations will require input from others, since finding and applying the correct schema is not a 1 to 1 match (not easy). Not sure when would be the right time. 

Below is an example of a few schemas on Schema.org, and below that are examples on how involved it can become from basic HTML.  

 - [GovernmentOrganization](https://schema.org/GovernmentOrganization)
 - [Organization](https://schema.org/Organization)
 - [Government Service](https://schema.org/GovernmentService )
 - [Digital Document](https://schema.org/DigitalDocument)
 
The Google tool will not help beyond copyright, authors, and dates, It can get involved, see example below: 

This is simple HTML on a site. 

``` 
<div>
NYC Food Service Establishment Permit, issued by Department of Health and Mental Hygiene.
(issued through NYC Food Service Establishment Permit Service; valid in New York for 1 year).
</div>
```

This is that HTML in JSON-LD
```
<script type="application/ld+json">
{
  "@context": "https://schema.org",
  "@type": "GovernmentService",
  "name": "Veterans Affairs Emergency Mental Health",
  "serviceType": "Psychiatric Emergency Services",
  "serviceOperator": {
    "@type": "GovernmentOrganization",
    "name": "US Department of Veterans Affairs"
  },
  "areaServed": {
    "@type": "AdministrativeArea",
    "name": "Massachusetts"
  },
  "audience": {
    "@type": "Audience",
    "name": "Veterans"
  },
  "availableChannel": {
    "@type": "ServiceChannel",
    "name": "Urgent Care Clinic",
    "availableLanguage": {
      "@type": "Language",
      "name": "Spanish",
      "alternateName": "es"
    },
    "serviceLocation": {
      "@type": "Hospital",
      "name": "VA Boston -- West Roxbury",
      "address": {
        "@type": "PostalAddress",
        "streetAddress": "1400 VFW Parkway",
        "addressLocality": "West Roxbury",
        "addressRegion": "MA",
        "postalCode": "02132"
      }
    }
  }
}
</script>
```

and this is that HTML in Microdata (notice the schema linking in multiple `itemscope`)

``` html
<div itemscope itemtype="https://schema.org/GovernmentPermit">
  <span itemprop="name">NYC Food Service Establishment Permit</span>
  <div itemprop="issuedBy" itemscope itemtype="https://schema.org/GovernmentOrganization">
    <span itemprop="name">Department of Health and Mental Hygiene"</span>
  </div>
  <div itemprop="issuedThrough" itemscope itemtype="https://schema.org/GovernmentService">
    <span itemprop="name">NYC Food Service Establishment Permit Service</span>
   </div>
  <div itemprop="validIn" itemscope itemtype="https://schema.org/AdministrativeArea">
    <span itemprop="name">New York</span>
  </div>
  <time itemprop="validFor" datetime="P1Y">1 year</time>
</div>
```

@TheInfinityBeyonder  @SuGhadiali

**Comment by id2win** [comment]
Closing as not planned. Return on investment is not worth the level of effort. Maybe a consideration for later.

**Comment by claytonjbarnette** [comment]
## Ready for review - PoC

@id2win @KonradMiles 

Though not planned, I have the initial PoC JSON-LD Structured Data ready for review.

The branch that contains the JSON-LD Structured Data is located here:  [1030-structured-data-preview](https://github.com/GSA/idmanagement.gov/tree/1030-structured-data-preview)

Below is a link to the above branch validated through the schema.org validator: 
- [Schedma.org Validated Preview Branch](https://validator.schema.org/#url=https%3A%2F%2Ffederalist-cf03235f-a054-4178-aafb-4e1e61e0d42c.sites.pages.cloud.gov%2Fpreview%2Fgsa%2Fidmanagement.gov%2F1030-structured-data-preview%2F)

The information on the right is the JSON-LD that is just on the homepage of the site, the information on the left is the HTML of the homepage seen by the Schema.org validator. 

As you can see, I compared to what others used on their site and worked from there, below is a example of what was on another site, which is very little information: 

```
{
"@context":"http://schema.org",
"@type":"Organization",
"name":"Defense Logistics Agency",
"url":"http://www.dla.mil/",
"sameAs":["http://www.facebook.com/dla.mil","https://twitter.com/DLAMIL","https://www.youtube.com/user/dodlogisticsagency"]
}
```

Next is what I was able to pull together after days of pouring through multiple++ schemas on [Schema.org](https://www.schema.org), of course, this information needs to be validated for correctness and to see if it is sufficient to what you what on the site and what SiteImprove is expecting.

```
<script type="application/ld+json">
{
"@context":"http://schema.org",
"@type":"GovernmentOrganization",
"name":"ID Management.gov",
"parentOrganization":"U.S. General Services Administration",
"department":"Office of Government-wide Policy",
"url":"http://www.idmanagement.gov/",
"email":"icam at gsa.gov",
"description": "IDManagement.gov is a collaboration between the Federal CIO Council and GSA to develop and share leading practices in protecting federal IT systems.",
"keywords":"GSA, FICAM, FPKI, ICAM, FIPS 201, PKI, PIV-I, PACS, Playbooks, Federal Identity, Credentials, Identity Management, Identity Lifecycle, Vendors, Acquisition Professionals, Program Managers, Privileged Identity, Single Sign On, User Authrization, Identity Lifecycle Management",
"address": {
    "@type": "PostalAddress",
    "addressLocality": "Washington",
    "addressRegion": "DC",
    "postalCode": "20405",
    "streetAddress": "1800 F Street, NW"
  },
 "sameAs":["https://www.gsa.gov", "https://www.linkedin.com/company/gsa/", "https://www.facebook.com/GSA/", "https://www.instagram.com/usgsa/", "https://www.youtube.com/@usgsa", "https://twitter.com/USGSA"]
}
</script>

```

Not very rewarding for marketability, but strong enough to give a search engine something to do, if all is good, then the JSON-LD Structured Data is ready for the homepage only.


@SuGhadiali @TheInfinityBeyonder
